CREATE TABLE IF NOT EXISTS device (
    id BIGSERIAL NOT NULL PRIMARY KEY,
    device_id VARCHAR UNIQUE NOT NULL,
    brand VARCHAR NOT NULL,
    name VARCHAR(50) NOT NULL,
    created_on TIMESTAMP NOT NULL
);